export const TEAM_LIST_REQUEST = "TEAM_LIST_REQUEST";
export const TEAM_LIST_SUCCESS = "TEAM_LIST_SUCCESS";
export const TEAM_LIST_FAIL = "TEAM_LIST_FAIL";

export const TEAM_DETAILS_REQUEST = "TEAM_DETAILS_REQUEST";
export const TEAM_DETAILS_SUCCESS = "TEAM_DETAILS_SUCCESS";
export const TEAM_DETAILS_FAIL = "TEAM_DETAILS_FAIL";

export const TEAM_MEMBERS_REQUEST = "TEAM_MEMBERS_REQUEST";
export const TEAM_MEMBERS_SUCCESS = "TEAM_MEMBERS_SUCCESS";
export const TEAM_MEMBERS_FAIL = "TEAM_MEMBERS_FAIL";

export const TEAM_MEMBERS_ALL_REQUEST = "TEAM_MEMBERS_ALL_REQUEST";
export const TEAM_MEMBERS_ALL_SUCCESS = "TEAM_MEMBERS_ALL_SUCCESS";
export const TEAM_MEMBERS_ALL_FAIL = "TEAM_MEMBERS_ALL_FAIL";

export const TEAM_MEMBER_DELETE_REQUEST = "TEAM_MEMBER_DELETE_REQUEST";
export const TEAM_MEMBER_DELETE_SUCCESS = "TEAM_MEMBER_DELETE_SUCCESS";
export const TEAM_MEMBER_DELETE_FAIL = "TEAM_MEMBER_DELETE_FAIL";

export const TEAM_MEMBER_ADD_REQUEST = "TEAM_MEMBER_ADD_REQUEST";
export const TEAM_MEMBER_ADD_SUCCESS = "TEAM_MEMBER_ADD_SUCCESS";
export const TEAM_MEMBER_ADD_FAIL = "TEAM_MEMBER_ADD_FAIL";

export const TEAM_ADD_REQUEST = "TEAM_ADD_REQUEST";
export const TEAM_ADD_SUCCESS = "TEAM_ADD_SUCCESS";
export const TEAM_ADD_FAIL = "TEAM_ADD_FAIL";

export const TEAM_DELETE_REQUEST = "TEAM_DELETE_REQUEST";
export const TEAM_DELETE_SUCCESS = "TEAM_DELETE_SUCCESS";
export const TEAM_DELETE_FAIL = "TEAM_DELETE_FAIL";
